name: 'Check PR title'
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: naveenk1223/action-pr-title@master
        with:
          regex: '.+' # Regex the title should match.
          allowed_prefixes: 'release,feature,change,fix' # title should start with the given prefix
          prefix_case_sensitive: false # title prefix are case insensitive
